modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    authors = "${mod_authors}"
    credits = "Mod originale di KingTrapinch, porting a 1.21.1 di Axten"
    description = '''${mod_description}'''

[[mixins]]
    config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies."${mod_id}"]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies."${mod_id}"]]
    modId = "tfc"
    type = "required"
    versionRange = "${tfc_version_range}"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies."${mod_id}"]]
    modId = "cobblemon"
    type = "required"
    versionRange = "${cobblemon_version_range}"
    ordering = "AFTER"
    side = "BOTH"
